In [2]:
# Dependencies
import os
import requests
import pymongo
import pandas as pd
import csv
import datetime as dt
from sqlalchemy import create_engine
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import inspect, func
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

In [3]:
# create the database engine
#engine = create_engine("sqlite:///../Resources/dow.sqlite", echo=False)

In [4]:
# create an inspector for the engine
#inspector = inspect(engine)
#inspector.get_table_names()

In [5]:
# Get a list of column names and types
#columns = inspector.get_columns('dow')
#for c in columns:
#    print(c['name'], c["type"])

In [6]:
# view all data
#engine.execute('SELECT * FROM dow LIMIT 5').fetchall()

In [7]:
# Reflect Database into ORM class
#Base = automap_base()
#Base.prepare(engine, reflect=True)
#Dow = Base.classes.dow

In [8]:
# review CSV files

In [9]:
# make dataframes out of CSV files

In [10]:
# put new data frames into sql database

In [11]:
# verify that sql database works

In [12]:
query_url = 'https://data.kcmo.org/resource/dmjw-d28i.json'
response = requests.get(query_url).json()

In [13]:
crime_data = pd.read_csv('crimedata.csv')

In [14]:
crime_df = pd.DataFrame(crime_data)
crime_df.head()

,:@computed_region_9t2m_phkm,:@computed_region_kk66_ngf4,:@computed_region_my34_vmp8,:@computed_region_w4hf_t6bp,address,age,area,beat,city,description,...,offense,race,rep_dist,report_no,reported_date,reported_time,sex,to_date,to_time,zip_code
0,NaN,NaN,NaN,NaN,3900 MYRTLE AV,NaN,EPD,334.0,KANSAS CITY,Possession/Sale/Dist,...,1849,NaN,PJ3211,180066852,2018-08-30T00:00:00.000,04:58,NaN,NaN,NaN,64127
1,NaN,NaN,NaN,NaN,00 E 32 ST,68.0,CPD,135.0,KANSAS CITY,Non Aggravated Assau,...,801,W,PJ2580,180017833,2018-03-07T00:00:00.000,19:25,M,2018-03-07T00:00:00.000,19:25,64111
2,2.0,181.0,7.0,98.0,7700 E 75 ST,57.0,MPD,243.0,KANSAS CITY,Misc Violation,...,2601,B,PJ5738,180004903,2018-01-20T00:00:00.000,17:03,F,NaN,NaN,64138
3,2.0,175.0,7.0,157.0,5800 BELLEFONTAINE AV,28.0,MPD,223.0,KANSAS CITY,Aggravated Assault (,...,401,B,PJ4665,180011611,2018-02-16T00:00:00.000,16:16,F,NaN,NaN,64130
4,NaN,NaN,NaN,NaN,E BANNISTER RD and BRISTOL AV,51.0,SPD,542.0,KANSAS CITY,Aggravated Assault (,...,401,B,PJ6485,180065046,2018-08-23T00:00:00.000,21:32,M,NaN,NaN,64138

In [15]:
crime_df = crime_df.drop([":@computed_region_9t2m_phkm", ":@computed_region_kk66_ngf4", ":@computed_region_my34_vmp8", 
                         ":@computed_region_w4hf_t6bp", "age", "race", "rep_dist", "sex", "to_date", "to_time"], axis=1)
crime_df.head()

,address,area,beat,city,description,dvflag,firearm_used_flag,from_date,from_time,ibrs,invl_no,involvement,location,offense,report_no,reported_date,reported_time,zip_code
0,3900 MYRTLE AV,EPD,334.0,KANSAS CITY,Possession/Sale/Dist,U,N,2018-08-30T00:00:00.000,04:58,35A,2,VIC,"3900 MYRTLE AV\nKANSAS CITY, 64127",1849,180066852,2018-08-30T00:00:00.000,04:58,64127
1,00 E 32 ST,CPD,135.0,KANSAS CITY,Non Aggravated Assau,N,N,2018-03-07T00:00:00.000,19:00,13B,1,VIC,"00 E 32 ST\nKANSAS CITY, 64111",801,180017833,2018-03-07T00:00:00.000,19:25,64111
2,7700 E 75 ST,MPD,243.0,KANSAS CITY,Misc Violation,U,N,2018-01-20T00:00:00.000,17:03,90Z,1,VIC,"7700 E 75 ST\nKANSAS CITY, 64138\n(38.987996,...",2601,180004903,2018-01-20T00:00:00.000,17:03,64138
3,5800 BELLEFONTAINE AV,MPD,223.0,KANSAS CITY,Aggravated Assault (,U,Y,2018-02-16T00:00:00.000,16:16,13A,1,VIC,"5800 BELLEFONTAINE AV\nKANSAS CITY, 64130\n(3...",401,180011611,2018-02-16T00:00:00.000,16:16,64130
4,E BANNISTER RD and BRISTOL AV,SPD,542.0,KANSAS CITY,Aggravated Assault (,U,Y,2018-08-23T00:00:00.000,21:32,13A,1,VIC,"E BANNISTER RD\nKANSAS CITY, 64138",401,180065046,2018-08-23T00:00:00.000,21:32,64138

In [16]:
from sqlalchemy import Column, Integer, String, Float

In [17]:
import pymysql
pymysql.install_as_MySQLdb()

engine = create_engine("mysql://127.0.0.1:3306")
conn = engine.connect()

Base.metadata.create_all(engine)
session = Session(bind=engine)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)") (Background on this error at: http://sqlalche.me/e/e3q8)

In [18]:
# SQL Alchemy
from sqlalchemy import create_engine

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()
PWD = 'YOUR PWD HERE'
USR = 'YOUR USERNAME HERE'
SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@localhost:3306/crimez'.format(USR, PWD)

# TO GET THIS PORTION TO WORK OPEN UP YOUR MYSQL Command Line Client
# Type the following into your CLC:
# GRANT all privileges on TESTDB.* to 'Max'@'localhost' IDENTIFIED BY 'maxkim' WITH GRANT OPTION;
# changing 'max' to your username and 'maxkim' to you password
engine = create_engine(SQLALCHEMY_DATABASE_URI)
conn = engine.connect()

crime_data = pd.read_sql("SELECT * FROM crimedata", conn)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)") (Background on this error at: http://sqlalche.me/e/e3q8)

In [19]:
crime_data.head()

,:@computed_region_9t2m_phkm,:@computed_region_kk66_ngf4,:@computed_region_my34_vmp8,:@computed_region_w4hf_t6bp,address,age,area,beat,city,description,...,offense,race,rep_dist,report_no,reported_date,reported_time,sex,to_date,to_time,zip_code
0,NaN,NaN,NaN,NaN,3900 MYRTLE AV,NaN,EPD,334.0,KANSAS CITY,Possession/Sale/Dist,...,1849,NaN,PJ3211,180066852,2018-08-30T00:00:00.000,04:58,NaN,NaN,NaN,64127
1,NaN,NaN,NaN,NaN,00 E 32 ST,68.0,CPD,135.0,KANSAS CITY,Non Aggravated Assau,...,801,W,PJ2580,180017833,2018-03-07T00:00:00.000,19:25,M,2018-03-07T00:00:00.000,19:25,64111
2,2.0,181.0,7.0,98.0,7700 E 75 ST,57.0,MPD,243.0,KANSAS CITY,Misc Violation,...,2601,B,PJ5738,180004903,2018-01-20T00:00:00.000,17:03,F,NaN,NaN,64138
3,2.0,175.0,7.0,157.0,5800 BELLEFONTAINE AV,28.0,MPD,223.0,KANSAS CITY,Aggravated Assault (,...,401,B,PJ4665,180011611,2018-02-16T00:00:00.000,16:16,F,NaN,NaN,64130
4,NaN,NaN,NaN,NaN,E BANNISTER RD and BRISTOL AV,51.0,SPD,542.0,KANSAS CITY,Aggravated Assault (,...,401,B,PJ6485,180065046,2018-08-23T00:00:00.000,21:32,M,NaN,NaN,64138

In [20]:
crime_data_2014 = pd.read_csv('KCPD_Crime_Data_2014.csv')
crime_data_2014.head()

,Report_No,Reported_Date,Reported Time,From_Date,From Time,To_Date,To Time,Offense,IBRS,Description,...,Involvement,Race,Sex,Age,Location 1,Firearm Used Flag,Neighborhood Census,Council Districts,County Boundary,Zip Codes
0,140092859,12/28/2014,19:36,12/22/2014,1:00,12/22/2014 0:00,21:30,670,23D,Stealing from Buildi,...,VIC,B,M,45.0,"3300 E 30 ST\nKANSAS CITY 64127\n(39.07141553,...",N,77.0,3.0,7.0,36.0
1,140003100,1/14/2014,12:30,1/12/2014,19:00,1/14/2014 0:00,11:00,702,240,Auto Theft,...,VIC,B,F,20.0,400 HIGHLAND AV\nKANSAS CITY 64106\n(39.110471...,N,135.0,3.0,7.0,75.0
2,140078116,10/28/2014,12:53,10/7/2014,14:00,NaN,NaN,1198,26C,Impersonation,...,VIC,W,F,43.0,"E INDEPENDENCE AV/E WINNER KANSAS CITY, RD 641...",N,123.0,3.0,7.0,19.0
3,140087038,12/4/2014,12:35,12/4/2014,12:35,NaN,NaN,401,13A,Aggravated Assault (,...,VIC,B,M,20.0,83 ST WAYNE AV\nKANSAS CITY 64130\n(39.0333197...,Y,175.0,2.0,7.0,157.0
4,140034949,5/22/2014,12:23,5/22/2014,12:20,5/22/2014 0:00,13:00,1546,520,Weapons Law Violatio,...,VIC,NaN,NaN,NaN,17 ST TOPPING AV\nKANSAS CITY 64127\n(39.08961...,Y,17.0,3.0,7.0,95.0

In [21]:
crime_data_2015 = pd.read_csv('KCPD_Crime_Data_2015.csv')
crime_data_2015.head()

,Report_No,Reported_Date,Reported Time,From_Date,From Time,To_Date,To Time,Offense,IBRS,Description,...,Sex,Age,Firearm Used Flag,Latitude,Longitude,Location 1,Neighborhood Census,Council Districts,County Boundary,Zip Codes
0,150015427,03/06/2015,0:02,03/06/2015,0:02,NaN,NaN,2601,90Z,Misc Violation,...,NaN,NaN,N,38.9767,-94.5767,"BROADWAY KANSAS CITY64131\n(38.9767, -94.5767)",197.0,2.0,7.0,163.0
1,70045155,09/21/2015,14:20,01/19/2015,NaN,NaN,NaN,401,13A,Aggravated Assault (,...,M,NaN,N,0.0000,0.0000,"99999(0.0, 0.0)",NaN,NaN,NaN,NaN
2,70045155,09/21/2015,14:20,01/19/2015,NaN,NaN,NaN,2001,90F,Family Offense,...,M,NaN,N,0.0000,0.0000,"99999(0.0, 0.0)",NaN,NaN,NaN,NaN
3,150057463,09/08/2015,1:17,09/08/2015,1:17,NaN,NaN,702,240,Auto Theft,...,U,NaN,N,39.0947,-94.5516,"E PROSPECT KANSAS CITY, AV 64126\n(39.0947, -9...",54.0,3.0,7.0,95.0
4,150033873,05/19/2015,0:21,05/19/2015,0:21,NaN,NaN,1849,35A,Possession/Sale/Dist,...,NaN,NaN,N,39.0735,-94.5461,"VICTOR KANSAS CITY, ST 64128\n(39.0735, -94.5461)",77.0,3.0,7.0,36.0

In [22]:
crime_data_2016 = pd.read_csv('KCPD_Crime_Data_2016.csv')
crime_data_2016.head()

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Sex,Age,Firearm Used Flag,Latitude,Longitude,Location 1,Neighborhood Census,Council Districts,County Boundary,Zip Codes
0,100034831,10/18/2016,20:35,10/18/2016,20:35,NaN,NaN,1352,280,Stolen Property OFFE,...,M,27.0,N,38.9983,-94.5429,"E CLEVELAND BL KANSAS CITY, AV 64130\n(38.9983...",131.0,2.0,7.0,151.0
1,120027507,10/25/2016,15:10,10/25/2016,14:00,NaN,NaN,1352,280,Stolen Property OFFE,...,NaN,NaN,N,39.0370,-94.5474,52 ST and MICHIGAN AV\nKANSAS CITY 64130\n(39....,175.0,3.0,7.0,157.0
2,120084496,05/28/2016,23:29,05/28/2016,23:29,NaN,NaN,1352,280,Stolen Property OFFE,...,M,35.0,N,39.0675,-94.5346,"E JACKSON BL KANSAS CITY, AV 64128\n(39.0675, ...",115.0,3.0,7.0,36.0
3,130056370,07/04/2016,1:37,07/03/2016,23:10,07/04/2016,0:47,1849,35A,Possession/Sale/Dist,...,NaN,NaN,N,39.0078,-94.4851,8500 BLUE PARKWAY\nKANSAS CITY 64133\n(39.0078...,18.0,2.0,7.0,37.0
4,130056370,07/04/2016,1:37,07/03/2016,23:10,07/04/2016,0:47,1849,35A,Possession/Sale/Dist,...,M,50.0,N,39.0078,-94.4851,8500 BLUE PARKWAY\nKANSAS CITY 64133\n(39.0078...,18.0,2.0,7.0,37.0

In [23]:
crime_data_2017 = pd.read_csv('KCPD_Crime_Data_2017.csv')
crime_data_2017.head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Rep_Dist,Area,DVFlag,Invl_No,Involvement,Race,Sex,Age,Firearm Used Flag,Location
0,170086272,10/05/2017,10:00,10/04/2017,16:00,10/05/2017,10:00,690,23H,Stealing All Other,...,PJ4582,MPD,U,1,SUS,U,U,NaN,N,"400 W 58 ST\nKANSAS CITY 64113\n(39.022397, -9..."
1,170026074,04/12/2017,13:01,03/20/2017,11:30,04/11/2017,00:45,630,23C,Stealing Shoplifting,...,PJ2875,EPD,U,1,VIC,NaN,NaN,NaN,N,3500 PROSPECT AV\nKANSAS CITY 64127
2,170003559,01/15/2017,02:35,01/15/2017,02:35,NaN,NaN,1850,35B,Possession of Drug E,...,PP0269,NPD,U,1,ARR,B,M,23.0,N,N NW GREEN HILLS RD\nKANSAS CITY 64152
3,170001089,01/05/2017,11:40,01/05/2017,11:40,NaN,NaN,1849,35A,Possession/Sale/Dist,...,PJ1046,CPD,U,1,VIC,NaN,NaN,NaN,N,"1100 TROOST AV\nKANSAS CITY 64106\n(39.10068, ..."
4,170007467,01/30/2017,13:04,01/27/2017,21:25,01/27/2017,22:30,670,23D,Stealing from Buildi,...,PJ2012,EPD,U,1,VIC,B,F,38.0,N,"4800 E 24 ST\nKANSAS CITY 64127\n(39.08209, -9..."